# Generated by Django 4.0.4 on 2022-07-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evuser', '0001_initial'),
        ('evcharger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charginginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField(verbose_name='충전량')),
                ('amount', models.IntegerField(verbose_name='충전금액')),
                ('start_dttm', models.DateTimeField(auto_now_add=True, verbose_name='충전시작일시')),
                ('end_dttm', models.DateTimeField(auto_now_add=True, verbose_name='충전완료일시')),
                ('cpname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evcharger.evcharger', verbose_name='충전기이름')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evuser.evuser', verbose_name='회원아이디')),
            ],
            options={
                'verbose_name': '충전정보',
                'verbose_name_plural': '충전정보',
                'db_table': 'evsp_charginginfo',
            },
        ),
    ]
