# Generated by Django 4.0.4 on 2022-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msglog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msglog',
            options={'verbose_name': '메세지로그정보', 'verbose_name_plural': '메세지로그정보'},
        ),
        migrations.AlterField(
            model_name='msglog',
            name='cpname',
            field=models.CharField(max_length=128, verbose_name='충전기번호'),
        ),
        migrations.AlterField(
            model_name='msglog',
            name='username',
            field=models.CharField(max_length=128, verbose_name='사용자명'),
        ),
    ]
